Added checks to improve openssf score (#98)

diff --git a/.github/workflows/onpullrequest.yml b/.github/workflows/onpullrequest.yml
--- a/.github/workflows/onpullrequest.yml
+++ b/.github/workflows/onpullrequest.yml
@@ -3,20 +3,34 @@ name: OnPullRequest
 on:
   pull_request:
 
+permissions: read-all
+
 jobs:
+
+  security-file-check:
+    runs-on: [ ubuntu-20.04 ]
+    steps:
+      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+        with:
+          fetch-depth: 0
+
+      - name: Check Security.md file
+        run: |
+          if [ ! -f ./Security.md ]; then
+            echo "Security.md file is missing"
+            exit 1
+          fi
+
   build-test-scan:
     runs-on: [ ubuntu-20.04 ]
+    needs: [ "security-file-check" ]
     env:
       http_proxy: ${{ secrets.HTTP_PROXY }}
       https_proxy: ${{ secrets.HTTPS_PROXY }}
       no_proxy: ${{ secrets.NO_PROXY }}
     steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-
       - name: Setup Go
-        uses: actions/setup-go@v4
+        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
         with:
           go-version: '1.22'
 
